version: '3.8'
name: "crismafronteiro"
services:
  server:
    build:
      context: .
    restart: always
    ports:
      - 0.0.0.0:8080:8080
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - myenv
    environment:
      - DATABASE_PASSWORD=Nnm3bziyDfQVbjyo
      - DATABASE_USER=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=default
    volumes:
      - ./.:/app

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=default
      - POSTGRES_PASSWORD=Nnm3bziyDfQVbjyo
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - myenv

secrets:
  myenv:
    file: .env

volumes:
  db-data: