version: '3.8'
name: "crismafronteiro"
services:
  server:
    image: felilfeps/crismafronteiro:dev
    restart: always
    ports:
      - 0.0.0.0:8080:8080
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - myenv
    volumes:
    - ./.:/app

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=default
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - myenv

secrets:
  myenv:
    file: ./secrets.env

volumes:
  db-data: